module.exports.sqlErrors = {
  DUPLICATE_ENTRY_CODE: "ER_DUP_ENTRY",
  FOREIGN_KEY_FAIL_CODE: "ER_NO_REFERENCED_ROW_2",
};

module.exports.serverErrors = {
  SERVER_ERROR_CODE: "SERVER_ERROR",
};

module.exports.dataValidationErrors = {
  STUDENT: {
    INVALID_ENROLLMENT_ID_CODE: 100,
    INVALID_ACCOUNT_PASSWORD_CODE: 200,
    INVALID_FIRST_NAME_CODE: 300,
    INVALID_LAST_NAME_CODE: 400,
    INVALID_MOBILE_NUMBER_CODE: 500,
    INVALID_TNP_EMAIL_CODE: 600,
    INVALID_GRADUATION_YEAR_CODE: 700,
  },
};
