const BackendEndpoints = {
  // Student Sign up and Login Module Backend Endpoints
  REACT_APP_STUDENT_REGISTRATION_API:
    process.env.REACT_APP_STUDENT_REGISTRATION_API,
  REACT_APP_STUDENT_LOGIN_API: process.env.REACT_APP_STUDENT_LOGIN_API,
  REACT_APP_STUDENT_LOGOUT_API: process.env.REACT_APP_STUDENT_LOGOUT_API,
  REACT_APP_GET_REFRESH_AUTH_STUDENT_TOKEN_API:
    process.env.REACT_APP_GET_REFRESH_AUTH_STUDENT_TOKEN_API,

  // Admin Sign up and Login Module Backend Endpoints
  REACT_APP_ADMIN_REGISTRATION_API:
    process.env.REACT_APP_ADMIN_REGISTRATION_API,
  REACT_APP_ADMIN_LOGIN_API: process.env.REACT_APP_ADMIN_LOGIN_API,
  REACT_APP_ADMIN_LOGOUT_API: process.env.REACT_APP_ADMIN_LOGOUT_API,
  REACT_APP_GET_REFRESH_AUTH_ADMIN_TOKEN_API:
    process.env.REACT_APP_GET_REFRESH_AUTH_ADMIN_TOKEN_API,

  // Student Dashboard Backend Endpoints
  STUDENT_ACCOUNT_FIRSTYEARRESULT_UPLOAD:
    process.env.REACT_APP_STUDENT_ACCOUNT_FIRSTYEARRESULT_UPLOAD,
  STUDENT_ACCOUNT_SECONDYEARRESULT_UPLOAD:
    process.env.REACT_APP_STUDENT_ACCOUNT_SECONDYEARRESULT_UPLOAD,
  STUDENT_ACCOUNT_THIRDYEARRESULT_UPLOAD:
    process.env.REACT_APP_STUDENT_ACCOUNT_THIRDYEARRESULT_UPLOAD,
  STUDENT_ACCOUNT_FINALYEARRESULT_UPLOAD:
    process.env.REACT_APP_STUDENT_ACCOUNT_FINALYEARRESULT_UPLOAD,

  // Tokens
  AUTH_ADMIN_ACCESS_TOKEN: process.env.REACT_APP_AUTH_ADMIN_ACCESS_TOKEN,
  AUTH_ADMIN_REFRESH_TOKEN: process.env.REACT_APP_AUTH_ADMIN_REFRESH_TOKEN,
  ADMIN: process.env.REACT_APP_ADMIN,
  STUDENT: process.env.REACT_APP_STUDENT,
  AUTH_STUDENT_ACCESS_TOKEN: process.env.REACT_APP_AUTH_STUDENT_ACCESS_TOKEN,
  AUTH_STUDENT_REFRESH_TOKEN: process.env.REACT_APP_AUTH_STUDENT_REFRESH_TOKEN,
};

export default BackendEndpoints;
